#############################################################################
# Makefile for building: FileServer.app/Contents/MacOS/FileServer
# Generated by qmake (3.0) (Qt 5.4.1)
# Project:  FileServer.pro
# Template: app
# Command: /Users/vlad/Documents/Qt/5.4/clang_64/bin/qmake -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile FileServer.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.7 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.7 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I. -I../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers -I../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers -I../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers -I../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/AGL.framework/Headers -I../../Qt/5.4/clang_64/mkspecs/macx-clang -F/Users/vlad/Documents/Qt/5.4/clang_64/lib
QMAKE         = /Users/vlad/Documents/Qt/5.4/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = FileServer1.0.0
DISTDIR = /Users/vlad/Documents/QtProjects/FileServer/.tmp/FileServer1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -mmacosx-version-min=10.7 -Wl,-rpath,/Users/vlad/Documents/Qt/5.4/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/vlad/Documents/Qt/5.4/clang_64/lib -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework QtNetwork -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		myserver.cpp qrc_templates.cpp \
		moc_myserver.cpp
OBJECTS       = main.o \
		myserver.o \
		qrc_templates.o \
		moc_myserver.o
DIST          = ../../Qt/5.4/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt/5.4/clang_64/mkspecs/qdevice.pri \
		../../Qt/5.4/clang_64/mkspecs/features/device_config.prf \
		../../Qt/5.4/clang_64/mkspecs/common/shell-unix.conf \
		../../Qt/5.4/clang_64/mkspecs/common/unix.conf \
		../../Qt/5.4/clang_64/mkspecs/common/mac.conf \
		../../Qt/5.4/clang_64/mkspecs/common/macx.conf \
		../../Qt/5.4/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt/5.4/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt/5.4/clang_64/mkspecs/common/clang.conf \
		../../Qt/5.4/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt/5.4/clang_64/mkspecs/qconfig.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/5.4/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt/5.4/clang_64/mkspecs/features/qt_config.prf \
		../../Qt/5.4/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt/5.4/clang_64/mkspecs/features/spec_post.prf \
		../../Qt/5.4/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt/5.4/clang_64/mkspecs/features/default_pre.prf \
		../../Qt/5.4/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt/5.4/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt/5.4/clang_64/mkspecs/features/default_post.prf \
		../../Qt/5.4/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt/5.4/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt/5.4/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt/5.4/clang_64/mkspecs/features/warn_on.prf \
		../../Qt/5.4/clang_64/mkspecs/features/qt.prf \
		../../Qt/5.4/clang_64/mkspecs/features/resources.prf \
		../../Qt/5.4/clang_64/mkspecs/features/moc.prf \
		../../Qt/5.4/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt/5.4/clang_64/mkspecs/features/uic.prf \
		../../Qt/5.4/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt/5.4/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt/5.4/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt/5.4/clang_64/mkspecs/features/exceptions.prf \
		../../Qt/5.4/clang_64/mkspecs/features/yacc.prf \
		../../Qt/5.4/clang_64/mkspecs/features/lex.prf \
		FileServer.pro myserver.h main.cpp \
		myserver.cpp
QMAKE_TARGET  = FileServer
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = FileServer.app/Contents/MacOS/FileServer

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk \
		-mmacosx-version-min=10.7 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET):  $(OBJECTS)  
	@test -d FileServer.app/Contents/MacOS/ || mkdir -p FileServer.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: FileServer.pro ../../Qt/5.4/clang_64/mkspecs/macx-clang/qmake.conf ../../Qt/5.4/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt/5.4/clang_64/mkspecs/qdevice.pri \
		../../Qt/5.4/clang_64/mkspecs/features/device_config.prf \
		../../Qt/5.4/clang_64/mkspecs/common/shell-unix.conf \
		../../Qt/5.4/clang_64/mkspecs/common/unix.conf \
		../../Qt/5.4/clang_64/mkspecs/common/mac.conf \
		../../Qt/5.4/clang_64/mkspecs/common/macx.conf \
		../../Qt/5.4/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt/5.4/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt/5.4/clang_64/mkspecs/common/clang.conf \
		../../Qt/5.4/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt/5.4/clang_64/mkspecs/qconfig.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/5.4/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt/5.4/clang_64/mkspecs/features/qt_config.prf \
		../../Qt/5.4/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt/5.4/clang_64/mkspecs/features/spec_post.prf \
		../../Qt/5.4/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt/5.4/clang_64/mkspecs/features/default_pre.prf \
		../../Qt/5.4/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt/5.4/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt/5.4/clang_64/mkspecs/features/default_post.prf \
		../../Qt/5.4/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt/5.4/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt/5.4/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt/5.4/clang_64/mkspecs/features/warn_on.prf \
		../../Qt/5.4/clang_64/mkspecs/features/qt.prf \
		../../Qt/5.4/clang_64/mkspecs/features/resources.prf \
		../../Qt/5.4/clang_64/mkspecs/features/moc.prf \
		../../Qt/5.4/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt/5.4/clang_64/mkspecs/features/uic.prf \
		../../Qt/5.4/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt/5.4/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt/5.4/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt/5.4/clang_64/mkspecs/features/exceptions.prf \
		../../Qt/5.4/clang_64/mkspecs/features/yacc.prf \
		../../Qt/5.4/clang_64/mkspecs/features/lex.prf \
		FileServer.pro \
		templates.qrc \
		/Users/vlad/Documents/Qt/5.4/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Users/vlad/Documents/Qt/5.4/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/vlad/Documents/Qt/5.4/clang_64/lib/QtCore.framework/QtCore.prl \
		/Users/vlad/Documents/Qt/5.4/clang_64/lib/QtNetwork.framework/QtNetwork.prl
	$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile FileServer.pro
../../Qt/5.4/clang_64/mkspecs/features/spec_pre.prf:
../../Qt/5.4/clang_64/mkspecs/qdevice.pri:
../../Qt/5.4/clang_64/mkspecs/features/device_config.prf:
../../Qt/5.4/clang_64/mkspecs/common/shell-unix.conf:
../../Qt/5.4/clang_64/mkspecs/common/unix.conf:
../../Qt/5.4/clang_64/mkspecs/common/mac.conf:
../../Qt/5.4/clang_64/mkspecs/common/macx.conf:
../../Qt/5.4/clang_64/mkspecs/common/gcc-base.conf:
../../Qt/5.4/clang_64/mkspecs/common/gcc-base-mac.conf:
../../Qt/5.4/clang_64/mkspecs/common/clang.conf:
../../Qt/5.4/clang_64/mkspecs/common/clang-mac.conf:
../../Qt/5.4/clang_64/mkspecs/qconfig.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_core.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_help.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_location.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_network.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_script.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt/5.4/clang_64/mkspecs/features/qt_functions.prf:
../../Qt/5.4/clang_64/mkspecs/features/qt_config.prf:
../../Qt/5.4/clang_64/mkspecs/macx-clang/qmake.conf:
../../Qt/5.4/clang_64/mkspecs/features/spec_post.prf:
../../Qt/5.4/clang_64/mkspecs/features/exclusive_builds.prf:
../../Qt/5.4/clang_64/mkspecs/features/default_pre.prf:
../../Qt/5.4/clang_64/mkspecs/features/mac/default_pre.prf:
../../Qt/5.4/clang_64/mkspecs/features/resolve_config.prf:
../../Qt/5.4/clang_64/mkspecs/features/default_post.prf:
../../Qt/5.4/clang_64/mkspecs/features/mac/sdk.prf:
../../Qt/5.4/clang_64/mkspecs/features/mac/default_post.prf:
../../Qt/5.4/clang_64/mkspecs/features/mac/objective_c.prf:
../../Qt/5.4/clang_64/mkspecs/features/warn_on.prf:
../../Qt/5.4/clang_64/mkspecs/features/qt.prf:
../../Qt/5.4/clang_64/mkspecs/features/resources.prf:
../../Qt/5.4/clang_64/mkspecs/features/moc.prf:
../../Qt/5.4/clang_64/mkspecs/features/unix/opengl.prf:
../../Qt/5.4/clang_64/mkspecs/features/uic.prf:
../../Qt/5.4/clang_64/mkspecs/features/unix/thread.prf:
../../Qt/5.4/clang_64/mkspecs/features/mac/rez.prf:
../../Qt/5.4/clang_64/mkspecs/features/testcase_targets.prf:
../../Qt/5.4/clang_64/mkspecs/features/exceptions.prf:
../../Qt/5.4/clang_64/mkspecs/features/yacc.prf:
../../Qt/5.4/clang_64/mkspecs/features/lex.prf:
FileServer.pro:
templates.qrc:
/Users/vlad/Documents/Qt/5.4/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Users/vlad/Documents/Qt/5.4/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/vlad/Documents/Qt/5.4/clang_64/lib/QtCore.framework/QtCore.prl:
/Users/vlad/Documents/Qt/5.4/clang_64/lib/QtNetwork.framework/QtNetwork.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile FileServer.pro

qmake_all: FORCE

FileServer.app/Contents/PkgInfo: 
	@test -d FileServer.app/Contents || mkdir -p FileServer.app/Contents
	@$(DEL_FILE) FileServer.app/Contents/PkgInfo
	@echo "APPL????" >FileServer.app/Contents/PkgInfo
FileServer.app/Contents/Resources/empty.lproj: 
	@test -d FileServer.app/Contents/Resources || mkdir -p FileServer.app/Contents/Resources
	@touch FileServer.app/Contents/Resources/empty.lproj
	
FileServer.app/Contents/Info.plist: 
	@test -d FileServer.app/Contents || mkdir -p FileServer.app/Contents
	@$(DEL_FILE) FileServer.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.FileServer,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,FileServer,g" -e "s,@TYPEINFO@,????,g" ../../Qt/5.4/clang_64/mkspecs/macx-clang/Info.plist.app >FileServer.app/Contents/Info.plist

all: Makefile \
		FileServer.app/Contents/PkgInfo \
		FileServer.app/Contents/Resources/empty.lproj \
		FileServer.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents templates.qrc $(DISTDIR)/
	$(COPY_FILE) --parents myserver.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp myserver.cpp $(DISTDIR)/


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r FileServer.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all: qrc_templates.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_templates.cpp
qrc_templates.cpp: templates.qrc \
		index.html
	/Users/vlad/Documents/Qt/5.4/clang_64/bin/rcc -name templates templates.qrc -o qrc_templates.cpp

compiler_moc_header_make_all: moc_myserver.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_myserver.cpp
moc_myserver.cpp: ../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/QtNetwork \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qabstractnetworkcache.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qhttpmultipart.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworkaccessmanager.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworkcookie.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworkcookiejar.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworkdiskcache.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworkreply.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworkrequest.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworkconfigmanager.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworkconfiguration.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworksession.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qauthenticator.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qdnslookup.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qhostaddress.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qhostinfo.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworkinterface.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworkproxy.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qabstractsocket.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qlocalserver.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qlocalsocket.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qtcpserver.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qtcpsocket.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qudpsocket.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qssl.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qsslcertificate.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qsslcertificateextension.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qsslcipher.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qsslconfiguration.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qsslerror.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qsslkey.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qsslsocket.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qtnetworkversion.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/QTcpSocket \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QByteArray \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qbytearray.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QDebug \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QPushButton \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qpushbutton.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QGridLayout \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgridlayout.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTextStream \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtextstream.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QIODevice \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qiodevice.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QProgressBar \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qprogressbar.h \
		myserver.h
	/Users/vlad/Documents/Qt/5.4/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/vlad/Documents/Qt/5.4/clang_64/mkspecs/macx-clang -I/Users/vlad/Documents/QtProjects/FileServer -I/Users/vlad/Documents/Qt/5.4/clang_64/lib/QtWidgets.framework/Headers -I/Users/vlad/Documents/Qt/5.4/clang_64/lib/QtGui.framework/Headers -I/Users/vlad/Documents/Qt/5.4/clang_64/lib/QtNetwork.framework/Headers -I/Users/vlad/Documents/Qt/5.4/clang_64/lib/QtCore.framework/Headers -F/Users/vlad/Documents/Qt/5.4/clang_64/lib myserver.h -o moc_myserver.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp myserver.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/QtNetwork \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qabstractnetworkcache.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qhttpmultipart.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworkaccessmanager.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworkcookie.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworkcookiejar.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworkdiskcache.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworkreply.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworkrequest.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworkconfigmanager.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworkconfiguration.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworksession.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qauthenticator.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qdnslookup.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qhostaddress.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qhostinfo.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworkinterface.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworkproxy.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qabstractsocket.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qlocalserver.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qlocalsocket.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qtcpserver.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qtcpsocket.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qudpsocket.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qssl.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qsslcertificate.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qsslcertificateextension.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qsslcipher.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qsslconfiguration.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qsslerror.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qsslkey.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qsslsocket.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qtnetworkversion.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/QTcpSocket \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QByteArray \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qbytearray.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QDebug \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QPushButton \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qpushbutton.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QGridLayout \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgridlayout.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTextStream \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtextstream.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QIODevice \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qiodevice.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QProgressBar \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qprogressbar.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QApplication \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

myserver.o: myserver.cpp myserver.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/QtNetwork \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qabstractnetworkcache.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qhttpmultipart.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworkaccessmanager.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworkcookie.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworkcookiejar.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworkdiskcache.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworkreply.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworkrequest.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworkconfigmanager.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworkconfiguration.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworksession.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qauthenticator.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qdnslookup.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qhostaddress.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qhostinfo.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworkinterface.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworkproxy.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qabstractsocket.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qlocalserver.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qlocalsocket.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qtcpserver.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qtcpsocket.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qudpsocket.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qssl.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qsslcertificate.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qsslcertificateextension.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qsslcipher.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qsslconfiguration.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qsslerror.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qsslkey.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qsslsocket.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qtnetworkversion.h \
		../../Qt/5.4/clang_64/lib/QtNetwork.framework/Versions/5/Headers/QTcpSocket \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QByteArray \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qbytearray.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QDebug \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QPushButton \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qpushbutton.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QGridLayout \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qgridlayout.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTextStream \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtextstream.h \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QIODevice \
		../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qiodevice.h \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QProgressBar \
		../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qprogressbar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o myserver.o myserver.cpp

qrc_templates.o: qrc_templates.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_templates.o qrc_templates.cpp

moc_myserver.o: moc_myserver.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_myserver.o moc_myserver.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

